// LA FUNCION FLECHA, ES UNA MANERA DE ESCRIBIR UNA FUNCION EN JAVASCRIPT.
// - NOS DA UNA SINTAXIS MAS LIMPIA Y FACIL DE LEER


// SON FUNCIONES ANONIMAS(NO TIENEN NOMBRE), QUE SE PUEDEN O NO, ALMACENAR EN VARIABLES O CONSTANTES
const saludar = (nombre) => {
  console.log("Hola " + nombre);
  return 1;
};

saludar("Cinthya")