// FUNCIONES BASICAS

// LA FUNCION CONSTA DE TRES ELEMENTOS:
// 1. DATOS DE ENTRADA(PUEDE O NO HABER), A LOS DATOS DE ENTRADA(INPUT) QUE SE PIDEN, SE LES CONOCE COMO PARAMETROS
function saludar(nombre) {
  // 2. PROCESOS
  console.log("Hola " + nombre);
  // 3. VALOR RETORNADO O LA SALIDA DE LA FUNCION (OUTPUT)
  return 1;
};

// EJECUTAR LA FUNCION
saludar("Cinthya");
